In [21]:
####
"""
@author: Kannan Chandrasekaran (kach@microsoft.com) / kannaxp@gmail.com

Google's pre-trained model: https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit
http://w3cgeek.com/how-to-calculate-the-sentence-similarity-using-word2vec-model-of-gensim-with-python.html
"""

"\n@author: Kannan Chandrasekaran (kach@microsoft.com) / kannaxp@gmail.com\n\nGoogle's pre-trained model: https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit\nhttp://w3cgeek.com/how-to-calculate-the-sentence-similarity-using-word2vec-model-of-gensim-with-python.html\n"

In [22]:
import numpy as np
import gensim
from scipy import spatial
import pandas as pd
import re

In [23]:
w2v_model=gensim.models.KeyedVectors.load_word2vec_format(r'D:\workarea_kannan\word2vec\GoogleNews-vectors-negative300.bin', binary=True)

In [24]:
def preProcess(txt):
    
    stopwordsKB=['unknown','other']
    
    txt=str(txt)
    txt=txt.lower()
    #Replacing Special Chars
    txt=txt.replace(' ','_')
    txt = re.sub('\W+','', txt ) # L&T --> LT Vs L T
    txt=txt.replace('_',' ')
  
    tokens=txt.split(' ')
    tokens=[t for t in tokens if t not in stopwordsKB]
    return tokens

In [25]:

def avgFeatureVector(words, model=w2v_model, num_features=300):
        #function to average all words vectors in a given paragraph
        featureVec = np.zeros((num_features,), dtype="float32")
        nwords = 0

        #list containing names of words in the vocabulary
        index2word_set = set(model.index2word) #this is moved as input param for performance reasons
        for word in words:
            if word in index2word_set:
                nwords = nwords+1
                featureVec = np.add(featureVec, model[word])

        if(nwords>0):
            featureVec = np.divide(featureVec, nwords)
        return featureVec

In [26]:
#get average vector for sentence 1
s1 = "Further/Continuing Education"
s1_avg_vector = avgFeatureVector(preProcess(s1), model=w2v_model, num_features=300)

#get average vector for sentence 2
s2 = "Private Universities"
s2_avg_vector = avgFeatureVector(preProcess(s2), model=w2v_model, num_features=300)

sen1_sen2_similarity =  1-spatial.distance.cosine(s1_avg_vector,s2_avg_vector)
print(sen1_sen2_similarity)

0.43914058804512024

In [27]:
#get average vector for sentence 1
s1 = "Private Universities"
s1_avg_vector = avgFeatureVector(preProcess(s1), model=w2v_model, num_features=300)

#get average vector for sentence 2
s2 = "Software Publishers"
s2_avg_vector = avgFeatureVector(preProcess(s2), model=w2v_model, num_features=300)

sen1_sen2_similarity =  1-spatial.distance.cosine(s1_avg_vector,s2_avg_vector)
print(sen1_sen2_similarity)

0.26716935634613037

In [28]:
#df=pd.read_csv('Industry.csv')
df=pd.read_excel('MSSales_IndustryVerticalCategory.xlsx')
df=df[(df.IndustryID!=0) & (df.IndustryID!=9)]
df

,VerticalCategoryID,VerticalCategoryName,VerticalID,VerticalName,IndustryID,IndustryName,verticalcategorytxt
1,97,Public Universities,16,Higher Education,1,Higher Education,Higher Education Higher Education Public Unive...
2,137,Further/Continuing Education,16,Higher Education,1,Higher Education,Higher Education Higher Education Further/Cont...
3,478,Private Universities,16,Higher Education,1,Higher Education,Higher Education Higher Education Private Univ...
4,145,Hospitals,24,Health Provider,4,Health Provider,Health Provider Health Provider Hospitals
5,146,Private Physicians Practices,24,Health Provider,4,Health Provider,Health Provider Health Provider Private Physic...
...,...,...,...,...,...,...,...
194,471,Property Management,106,Real Estate,50,Real Estate,Real Estate Real Estate Property Management
195,472,Real Estate Brokerage,106,Real Estate,50,Real Estate,Real Estate Real Estate Real Estate Brokerage
196,199,Tax & Customs,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Tax & Cus..."
197,419,Reg/Permit/License/Inspection,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Reg/Permi..."
198,495,Economic Development,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Economic ..."

In [29]:
df['tokens']=df['verticalcategorytxt'].apply(preProcess)
df

,VerticalCategoryID,VerticalCategoryName,VerticalID,VerticalName,IndustryID,IndustryName,verticalcategorytxt,tokens
1,97,Public Universities,16,Higher Education,1,Higher Education,Higher Education Higher Education Public Unive...,"[higher, education, higher, education, public,..."
2,137,Further/Continuing Education,16,Higher Education,1,Higher Education,Higher Education Higher Education Further/Cont...,"[higher, education, higher, education, further..."
3,478,Private Universities,16,Higher Education,1,Higher Education,Higher Education Higher Education Private Univ...,"[higher, education, higher, education, private..."
4,145,Hospitals,24,Health Provider,4,Health Provider,Health Provider Health Provider Hospitals,"[health, provider, health, provider, hospitals]"
5,146,Private Physicians Practices,24,Health Provider,4,Health Provider,Health Provider Health Provider Private Physic...,"[health, provider, health, provider, private, ..."
...,...,...,...,...,...,...,...,...
194,471,Property Management,106,Real Estate,50,Real Estate,Real Estate Real Estate Property Management,"[real, estate, real, estate, property, managem..."
195,472,Real Estate Brokerage,106,Real Estate,50,Real Estate,Real Estate Real Estate Real Estate Brokerage,"[real, estate, real, estate, real, estate, bro..."
196,199,Tax & Customs,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Tax & Cus...","[tax, revenue, , finance, tax, , revenue, tax,..."
197,419,Reg/Permit/License/Inspection,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Reg/Permi...","[tax, revenue, , finance, tax, , revenue, regp..."
198,495,Economic Development,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Economic ...","[tax, revenue, , finance, tax, , revenue, econ..."

In [30]:
df['embeddings']=df['tokens'].apply(avgFeatureVector)
df

,VerticalCategoryID,VerticalCategoryName,VerticalID,VerticalName,IndustryID,IndustryName,verticalcategorytxt,tokens,embeddings
1,97,Public Universities,16,Higher Education,1,Higher Education,Higher Education Higher Education Public Unive...,"[higher, education, higher, education, public,...","[-0.09375, -0.05823517, 0.01340739, 0.20613606..."
2,137,Further/Continuing Education,16,Higher Education,1,Higher Education,Higher Education Higher Education Further/Cont...,"[higher, education, higher, education, further...","[-0.11035156, -0.068762206, -0.02878418, 0.152..."
3,478,Private Universities,16,Higher Education,1,Higher Education,Higher Education Higher Education Private Univ...,"[higher, education, higher, education, private...","[-0.10392252, -0.06502024, 0.022379557, 0.2104..."
4,145,Hospitals,24,Health Provider,4,Health Provider,Health Provider Health Provider Hospitals,"[health, provider, health, provider, hospitals]","[-0.06665039, -0.043847658, 0.08964844, 0.1124..."
5,146,Private Physicians Practices,24,Health Provider,4,Health Provider,Health Provider Health Provider Private Physic...,"[health, provider, health, provider, private, ...","[-0.08483887, 0.02040318, 0.07195173, 0.080496..."
...,...,...,...,...,...,...,...,...,...
194,471,Property Management,106,Real Estate,50,Real Estate,Real Estate Real Estate Property Management,"[real, estate, real, estate, property, managem...","[0.19156902, 0.055989582, -0.089029945, 0.0265..."
195,472,Real Estate Brokerage,106,Real Estate,50,Real Estate,Real Estate Real Estate Real Estate Brokerage,"[real, estate, real, estate, real, estate, bro...","[0.21554129, 0.09730748, -0.12820871, 0.044490..."
196,199,Tax & Customs,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Tax & Cus...","[tax, revenue, , finance, tax, , revenue, tax,...","[0.19566128, 0.019112723, -0.011605399, 0.0818..."
197,419,Reg/Permit/License/Inspection,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Reg/Permi...","[tax, revenue, , finance, tax, , revenue, regp...","[0.17001954, -0.0359375, 0.00055541995, 0.0435..."
198,495,Economic Development,73,Tax & Revenue,51,"Tax, Revenue & Finance","Tax, Revenue & Finance Tax & Revenue Economic ...","[tax, revenue, , finance, tax, , revenue, econ...","[0.10637556, -0.020738874, -0.018454416, 0.028..."

In [31]:
df['embeddings']=df['embeddings'].apply(list)
df=df[['VerticalCategoryID','verticalcategorytxt','embeddings']]

In [32]:
df.to_excel('MSS_Embeddings.xlsx',index=False)

In [33]:
df.to_csv('MSS_Embeddings.csv',index=False)

In [37]:
tmp1=df
tmp2=df
tmp1['i']=1
tmp2['i']=1

C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [38]:
tmp1

,VerticalCategoryID,verticalcategorytxt,embeddings,i
1,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1
2,137,Higher Education Higher Education Further/Cont...,"[-0.11035156, -0.068762206, -0.02878418, 0.152...",1
3,478,Higher Education Higher Education Private Univ...,"[-0.10392252, -0.06502024, 0.022379557, 0.2104...",1
4,145,Health Provider Health Provider Hospitals,"[-0.06665039, -0.043847658, 0.08964844, 0.1124...",1
5,146,Health Provider Health Provider Private Physic...,"[-0.08483887, 0.02040318, 0.07195173, 0.080496...",1
...,...,...,...,...
194,471,Real Estate Real Estate Property Management,"[0.19156902, 0.055989582, -0.089029945, 0.0265...",1
195,472,Real Estate Real Estate Real Estate Brokerage,"[0.21554129, 0.09730748, -0.12820871, 0.044490...",1
196,199,"Tax, Revenue & Finance Tax & Revenue Tax & Cus...","[0.19566128, 0.019112723, -0.011605399, 0.0818...",1
197,419,"Tax, Revenue & Finance Tax & Revenue Reg/Permi...","[0.17001954, -0.0359375, 0.00055541995, 0.0435...",1
198,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1

In [42]:
tmp3=tmp1.merge(tmp2,how='inner', on='i')
tmp3=tmp3[tmp3.VerticalCategoryID_x!=tmp3.VerticalCategoryID_y]
tmp3

,VerticalCategoryID_x,verticalcategorytxt_x,embeddings_x,i,VerticalCategoryID_y,verticalcategorytxt_y,embeddings_y
1,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,137,Higher Education Higher Education Further/Cont...,"[-0.11035156, -0.068762206, -0.02878418, 0.152..."
2,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,478,Higher Education Higher Education Private Univ...,"[-0.10392252, -0.06502024, 0.022379557, 0.2104..."
3,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,145,Health Provider Health Provider Hospitals,"[-0.06665039, -0.043847658, 0.08964844, 0.1124..."
4,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,146,Health Provider Health Provider Private Physic...,"[-0.08483887, 0.02040318, 0.07195173, 0.080496..."
5,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,198,Health Provider Health Provider Social & Human...,"[-0.025774274, -0.04876709, 0.030412946, 0.105..."
...,...,...,...,...,...,...,...
38803,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,470,Real Estate Real Estate Property Development,"[0.19091797, 0.043863934, -0.07521566, 0.03445..."
38804,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,471,Real Estate Real Estate Property Management,"[0.19156902, 0.055989582, -0.089029945, 0.0265..."
38805,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,472,Real Estate Real Estate Real Estate Brokerage,"[0.21554129, 0.09730748, -0.12820871, 0.044490..."
38806,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,199,"Tax, Revenue & Finance Tax & Revenue Tax & Cus...","[0.19566128, 0.019112723, -0.011605399, 0.0818..."
38807,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,419,"Tax, Revenue & Finance Tax & Revenue Reg/Permi...","[0.17001954, -0.0359375, 0.00055541995, 0.0435..."

In [46]:
def sim(row): 
    return 1-spatial.distance.cosine(row['embeddings_x'], row['embeddings_y'])

In [47]:
tmp3['sim']=tmp3.apply(sim, axis=1)

In [48]:
tmp3

,VerticalCategoryID_x,verticalcategorytxt_x,embeddings_x,i,VerticalCategoryID_y,verticalcategorytxt_y,embeddings_y,sim
1,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,137,Higher Education Higher Education Further/Cont...,"[-0.11035156, -0.068762206, -0.02878418, 0.152...",0.940732
2,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,478,Higher Education Higher Education Private Univ...,"[-0.10392252, -0.06502024, 0.022379557, 0.2104...",0.981116
3,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,145,Health Provider Health Provider Hospitals,"[-0.06665039, -0.043847658, 0.08964844, 0.1124...",0.443243
4,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,146,Health Provider Health Provider Private Physic...,"[-0.08483887, 0.02040318, 0.07195173, 0.080496...",0.438963
5,97,Higher Education Higher Education Public Unive...,"[-0.09375, -0.05823517, 0.01340739, 0.20613606...",1,198,Health Provider Health Provider Social & Human...,"[-0.025774274, -0.04876709, 0.030412946, 0.105...",0.438190
...,...,...,...,...,...,...,...,...
38803,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,470,Real Estate Real Estate Property Development,"[0.19091797, 0.043863934, -0.07521566, 0.03445...",0.409176
38804,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,471,Real Estate Real Estate Property Management,"[0.19156902, 0.055989582, -0.089029945, 0.0265...",0.370228
38805,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,472,Real Estate Real Estate Real Estate Brokerage,"[0.21554129, 0.09730748, -0.12820871, 0.044490...",0.312893
38806,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,199,"Tax, Revenue & Finance Tax & Revenue Tax & Cus...","[0.19566128, 0.019112723, -0.011605399, 0.0818...",0.933414
38807,495,"Tax, Revenue & Finance Tax & Revenue Economic ...","[0.10637556, -0.020738874, -0.018454416, 0.028...",1,419,"Tax, Revenue & Finance Tax & Revenue Reg/Permi...","[0.17001954, -0.0359375, 0.00055541995, 0.0435...",0.964176

In [49]:
tmp3.to_excel('MSS_embeddings_similarity.xlsx',index=False)