In [26]:
####
"""
@author: Kannan Chandrasekaran (kach@microsoft.com) / kannaxp@gmail.com

Google's pre-trained model: https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit
http://w3cgeek.com/how-to-calculate-the-sentence-similarity-using-word2vec-model-of-gensim-with-python.html
"""

"\n@author: Kannan Chandrasekaran (kach@microsoft.com) / kannaxp@gmail.com\n\nGoogle's pre-trained model: https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit\nhttp://w3cgeek.com/how-to-calculate-the-sentence-similarity-using-word2vec-model-of-gensim-with-python.html\n"

In [27]:
import numpy as np
import gensim
from scipy import spatial
import pandas as pd
import re

In [42]:

def avgFeatureVector(words, model=w2v_model, num_features=300):
        #function to average all words vectors in a given paragraph
        featureVec = np.zeros((num_features,), dtype="float32")
        nwords = 0

        #list containing names of words in the vocabulary
        index2word_set = set(model.index2word) #this is moved as input param for performance reasons
        for word in words:
            if word in index2word_set:
                nwords = nwords+1
                featureVec = np.add(featureVec, model[word])

        if(nwords>0):
            featureVec = np.divide(featureVec, nwords)
        return featureVec

In [8]:
w2v_model=gensim.models.KeyedVectors.load_word2vec_format(r'D:\workarea_kannan\word2vec\GoogleNews-vectors-negative300.bin', binary=True)

In [53]:
#get average vector for sentence 1
sentence_1 = "slow"
sentence_1_avg_vector = avg_feature_vector(sentence_1.split(), model=w2v_model, num_features=300)

#get average vector for sentence 2
sentence_2 = "device performance"
sentence_2_avg_vector = avg_feature_vector(sentence_2.split(), model=w2v_model, num_features=300)

sen1_sen2_similarity =  1 - spatial.distance.cosine(sentence_1_avg_vector,sentence_2_avg_vector)
print(sen1_sen2_similarity)

0.07165219634771347

In [57]:
#df=pd.read_csv('Industry.csv')
df=pd.read_csv('Industry_small.csv')
df

                                       Industry
0     Nonferrous wiredrawing and insulating,nsk
1                          Optical goods stores
2                       Animal aquaculture, nsk
3             Chocolate and cocoa products, nsk
4        Foreign bank and branches and agencies
...                                         ...
1490    Gas production and/or distribution, nsk
1491         Bags: uncoated paper and multiwall
1492         Structural clay products, nec, nsk
1493                      Farm machinery repair
1494                        Delicatessen stores

[1495 rows x 1 columns]

In [58]:
def preProcess(txt):
    
    stopwordsKB=['nsk','nec','n','ns']
    
    txt=str(txt)
    txt=txt.lower()
    #Replacing Special Chars
    txt=txt.replace(' ','_')
    txt = re.sub('\W+','', txt ) # L&T --> LT Vs L T
    txt=txt.replace('_',' ')
  
    tokens=txt.split(' ')
    tokens=[t for t in tokens if t not in stopwordsKB]
    return tokens

In [59]:
df['tokens']=df['Industry'].apply(preProcess)
df

,Industry,tokens
0,"Nonferrous wiredrawing and insulating,nsk","[nonferrous, wiredrawing, and, insulatingnsk]"
1,Optical goods stores,"[optical, goods, stores]"
2,"Animal aquaculture, nsk","[animal, aquaculture]"
3,"Chocolate and cocoa products, nsk","[chocolate, and, cocoa, products]"
4,Foreign bank and branches and agencies,"[foreign, bank, and, branches, and, agencies]"
...,...,...
1490,"Gas production and/or distribution, nsk","[gas, production, andor, distribution]"
1491,Bags: uncoated paper and multiwall,"[bags, uncoated, paper, and, multiwall]"
1492,"Structural clay products, nec, nsk","[structural, clay, products]"
1493,Farm machinery repair,"[farm, machinery, repair]"
1494,Delicatessen stores,"[delicatessen, stores]"

In [60]:
df['embeddings']=df['tokens'].apply(avgFeatureVector)
df

,Industry,tokens,embeddings
0,"Nonferrous wiredrawing and insulating,nsk","[nonferrous, wiredrawing, and, insulatingnsk]","[-0.19238281, 0.21582031, -0.12890625, 0.03686..."
1,Optical goods stores,"[optical, goods, stores]","[0.06591797, 0.19645183, -0.05802409, 0.109863..."
2,"Animal aquaculture, nsk","[animal, aquaculture]","[-0.13265991, 0.10406494, -0.15771484, 0.02319..."
3,"Chocolate and cocoa products, nsk","[chocolate, and, cocoa, products]","[-0.21077473, -0.0859375, 0.022949219, 0.28385..."
4,Foreign bank and branches and agencies,"[foreign, bank, and, branches, and, agencies]","[-0.012023926, 0.07836914, -0.0007019043, 0.16..."
...,...,...,...
1490,"Gas production and/or distribution, nsk","[gas, production, andor, distribution]","[-0.030395508, 0.03416443, -0.12402344, 0.0472..."
1491,Bags: uncoated paper and multiwall,"[bags, uncoated, paper, and, multiwall]","[-0.06567383, 0.23474121, -0.15146637, 0.09240..."
1492,"Structural clay products, nec, nsk","[structural, clay, products]","[-0.09488932, 0.055664062, 0.01969401, 0.17936..."
1493,Farm machinery repair,"[farm, machinery, repair]","[0.10058594, 0.17985027, -0.0024414062, -0.015..."
1494,Delicatessen stores,"[delicatessen, stores]","[0.07080078, 0.18945312, -0.0637207, 0.2856445..."

In [61]:
df['embeddings']=df['embeddings'].apply(list)

In [63]:
df.to_excel('Embeddings.xlsx',index=False)

In [64]:
df[['Industry','embeddings']].to_csv('Embeddings.csv',index=False)